### ISSUE TITLE
Header ref counts only itself

### ISSUE THREAD

**Issue by DutchPete** [shabegom/obsidian-reference-count#22]
Note 1 references a header, say `### Header text`, in note 2. Let's say there are no other notes referencing the header.

Note 2 shows the count of 1 next to the header, which is correct, but when I click on the number 1 it only lists note 2, i.e. itself, instead of note 1.

**Comment by shabegom** [comment]
@DutchPete What version are you using? If you upgrade to the latest is this still an issue? We made a bug change to how the refs are shown in 0.0.8

**Comment by GitMurf** [comment]
@shabegom I actually think this may still be an issue with 0.0.8 but should be fixed with the latest PR I submitted last night.

**Comment by DutchPete** [comment]
@shabegom, @GitMurf  sorry for the late reply, I was tied up with something else.
I am using version 0.08, and the issue seems to have evolved. In some notes the plugin number corresponds with the number of instances the ref is used, in others it does not. Below is a screenshot where you can see the plugin number is 3, but when I open it, only 1 instance is shown.

![image](https://user-images.githubusercontent.com/10794265/120467489-e8a54780-c3a8-11eb-8a0d-9b7961d8b5a0.png)

**Comment by DutchPete** [comment]
Here is that same paragraph in Edit mode:
![image](https://user-images.githubusercontent.com/10794265/120468202-a29cb380-c3a9-11eb-8289-f8949b22fdf2.png)

**Comment by DutchPete** [comment]
@Gitmuf's request "how it is referenced in the other note" makes sense, but strangely there is no link from Personalities#Klaus Schwab to Personalities_Gates_etc.

So, I am now completely confused as to what the alleged 3 links refer to, and how a dud link is included.
