### ISSUE TITLE
Version 0.09: kernel panic -> Version 0.1.4: slowww

### ISSUE THREAD

**Issue by DutchPete** [shabegom/obsidian-reference-count#35]
Just installed main, manifest, and styles. Activating in the setting does not work, causes a kernel panic instead.
MacOS 10.14, Obsidian 0.12.4.

**Comment by shabegom** [comment]
There is nothing in the plugin that should be causing a kernel panic. Can you paste in the crash report? I'm guessing it is related to the existing kernel panic issue in Obsidian.

**Comment by DutchPete** [comment]
I am not sure if I used the right term. What happens is that the plug-in freezes Obisidian.
If that IS a kernel plug-in, please tell me how I can get a crash report.

If that is NOT a kernel panic, please advise.

**Comment by wenlzhang** [comment]
I may have observed a related issue. Whenever this plugin is enabled, there are obvious delays in Obsidian when typing, scrolling the note in preview mode, etc. Disabling this plugin resolves the delay issue.

**Comment by DutchPete** [comment]
I closed this one too soon. The plug-in does not freeze Obsidian anymore, but it does slow it down: it takes several seconds before e.g. the cursor moves to a new spot where you have clicked.

So, there is progress, but its performance is still not acceptable.

I am on MacOS Mojave (10.14.6).

**Comment by shabegom** [comment]
@DutchPete very interesting. We tested this release across a bunch of different vaults with various amounts of references and didn't see slowdowns that were in the older version. Let's try to troubleshoot it.

Grab the main.js from this release: https://github.com/shabegom/obsidian-reference-count/releases/tag/666

It includes a lot of console logging to try and find the issue. replace the existing main.js, open the dev console: (View Menu > Toggle Developer Tools). Do whatever you were doing that caused a slow down and let me know what the dev console shows.

 Thanks!

**Comment by DutchPete** [comment]
@shabegom I downloaded the main.js you told me to and replaced the one in the plug-in folder, as you instructed.

I opened the dev console, but don't know how to View Menu > Toggle Developer Tools

![image](https://user-images.githubusercontent.com/10794265/131543235-1f9236b0-7151-4a1e-a223-b459217f1b6b.png)

**Comment by DutchPete** [comment]
I started typing some random text, and noticed the delay at the end of a sentence - the fullstop, and with clicking the `Enter` key to go to a new line.

Is this of any use?

![image](https://user-images.githubusercontent.com/10794265/131543949-9cdf3188-ff3c-4fbf-9b88-a89e663671aa.png)

**Comment by shabegom** [comment]
@DutchPete the logging should be something like:

```
cache changed re-indexing
indexBlockReferences: 1000ms
```
I'm particularly interested in the indexing time.

It should appear in the console you've got open. If you aren't seeing the logging, I must have messed up the main.js upload somehow...

**Comment by shabegom** [comment]
It is set to never index while you're typing and wait half a second until after typing stops to do the index. I'm just surprised it is causing lag. My guess is the indexing is taking much longer than it should be for some reason. Either because you have a large amount of notes, or references to index.

Ultimately, if it is causing a lag I'll need to go back and do some more work on the indexer. :(

**Comment by DutchPete** [comment]
Yes, I have some 400 - 500 notes, mosyt of which are very long.

**Comment by shabegom** [comment]
> Yes, I have some 400 - 500 notes, mosyt of which are very long.

We're testing on a vault of 2500+ notes including a full bible where each line has a block reference. So it is truly strange that you're seeing performance issues with 400-500 notes.

**Comment by DutchPete** [comment]
The delay problem I reported is in a folder I use most: 400 files. But the total number of items in the vault is 1500, incl. 200 PNG files and a number of PDFs too.

Many of the 400 files I mentioned are long: 3000-5000. I don't know if word count is important in indexing.

**Comment by wenlzhang** [comment]
@shabegom I have the logging info as follows:
```
cache changed, re-indexing
indexer.ts:42 indexBlockReferences: 1396.0927734375 ms
```
This is the longest index time that I have observed. For others that I have observed, they are mostly around `1100 ms` to `1200 ms`.

In my vault, there are around 3000 notes.

In this updated version of the plugin, the delay for me has improved, compared with the older version. Still, it feels a little weird when typing, as, occasionally, it stuck there for a short time.

**Comment by DutchPete** [comment]
@shabegom 
> Still, it feels a little weird when typing, as, occasionally, it stuck there for a short time.

What @wenlzhang is experiencing I am experiencing too. I notice this issue has not had any follow up for the past month; just out of interest: are you still working on it or is this going to remain as is?

**Comment by shabegom** [comment]
Hey @DutchPete I've been in the middle of a move and haven't had time to work on this plugin recently. I'll get back to it when I've got the time. If it is causing you issues I suggest disabling until I've figured out a fix.

**Comment by DutchPete** [comment]
OK Sam, no prob.

**Comment by shabegom** [comment]
@DutchPete @wenlzhang if you feel like testing out the prerelease for version 0.2.0 it can be found here: https://github.com/shabegom/obsidian-reference-count/releases/tag/0.2.0

This release moves indexing to a web worker, so should no longer cause any lag whatsoever. To manually install you need to download `main.js` and replace the one in .obsidian/plugins/block-refeference-counts. I'd love to know if this helps with the slow down you're experiencing. Thanks for the patience as I worked on this update.

**Comment by DutchPete** [comment]
@shabegom my 1<sup>st</sup> impression from a quick test is that the lag is gone. So far so good.

I will keep the plug-in enabled and will keep you informed. Thank you for your efforts, it is nice to work together this way.

**Comment by wenlzhang** [comment]
@shabegom Thanks for the update! I haven't observed obvious delays like before either so far. I will post further issues here, if any.

**Comment by wenlzhang** [comment]
@shabegom After a few days of testing, with the plugin both turned on and off, I still experience delays when typing, both in the editor and Command Palette. However, the frequency and duration of delays are much smaller than in the previous version. Still, when it happens, I can obviously feel the delay.

**Comment by shabegom** [comment]
I'm almost done yet another rewrite that uses a completely different indexing approach. In testing I'v greatly reduced the performance hit when doing an index. Hopefully will be out soon.

**Comment by shabegom** [comment]
0.3.0 has been released. It should be much much faster than the previous version! Let me know if it resolves the problem!

**Comment by wenlzhang** [comment]
Thanks for the update! I have been testing this new version in the past two weeks. I barely notice this issue any more.

**Comment by DutchPete** [comment]
I agree with @wenlzhang.

**Comment by shabegom** [comment]
Awesome, closing this issue!
