### ISSUE TITLE
Failed to load the plugin...

### ISSUE THREAD

**Issue by BragatteMAS** [shabegom/obsidian-reference-count#36]
https://www.loom.com/share/50925bb50ae0474a9b46c7db19cb80d0

**Comment by shabegom** [comment]
Please try 0.1.4

**Comment by shabegom** [comment]
@BragatteMAS instead of downloading the zip, download each file separately:

main.js
style.css
manifest.json

and copy those into a folder in the plugins directory. I hope this works!

**Comment by BragatteMAS** [comment]
Release Community Plugin Submission · shabegom/obsidian-reference-count - Watch
Video <https://www.loom.com/share/ce45896c858945d28a65af9cd71f6386>
<https://www.loom.com/share/ce45896c858945d28a65af9cd71f6386>
[image: image.gif]

At,te.

MSc. Bragatte, M.A.S.

Doutorando no Núcleo de Imunoinformática do Departamento de Genética
<http://www.ufrgs.br/ppgbm>.

Ph.D. studentat nucleus of Immunoinformatics from the department of
genetics and molecular biology <http://www.ufrgs.br/ppgbm>UFRGS

***@***.***

***@***.***

Bragatte_page <https://bit.ly/bragatte_page>

+ 55 (51) 9 9718 0058

<https://www.researchgate.net/profile/Marcelo_Bragatte>
<http://lattes.cnpq.br/9594590199370154>
<https://www.linkedin.com/in/bragatte/>
<https://twitter.com/MarceloBragatte> <https://www.facebook.com/BragatteMAS>
<https://www.instagram.com/marcelo_bragatte/?hl=pt-br>





[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
31/08/21
19:44:45

**Comment by BragatteMAS** [comment]
Sorry, my sound fail. However, I think that I pass the idea.

At,te.

MSc. Bragatte, M.A.S.

Doutorando no Núcleo de Imunoinformática do Departamento de Genética
<http://www.ufrgs.br/ppgbm>.

Ph.D. studentat nucleus of Immunoinformatics from the department of
genetics and molecular biology <http://www.ufrgs.br/ppgbm>UFRGS

***@***.***

***@***.***

Bragatte_page <https://bit.ly/bragatte_page>

+ 55 (51) 9 9718 0058

<https://www.researchgate.net/profile/Marcelo_Bragatte>
<http://lattes.cnpq.br/9594590199370154>
<https://www.linkedin.com/in/bragatte/>
<https://twitter.com/MarceloBragatte> <https://www.facebook.com/BragatteMAS>
<https://www.instagram.com/marcelo_bragatte/?hl=pt-br>





[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality8&>
Sender
notified by Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality8&>
31/08/21
19:52:18
