### ISSUE TITLE
Heading reference won't work if heading contains a special character

### ISSUE THREAD

**Issue by Cheloggs** [shabegom/obsidian-reference-count#38]
0.1.4

Obsidian supports special characters in headings and links to headings, but your plugin won't work with headings that do contain some special characters, in my particular case `'`. I do understand this is a minor issue in english but some languages make extensive use of `'`.

I hope this is clear enough, and thank you for your awesome plug in!

EDIT: Also the `+` character breaks it

**Comment by shabegom** [comment]
Thanks for reporting @Cheloggs! It's been a challenge to capture all the different characters in headings. I'm releasing 0.1.5 which should now grab + and ' and hopefully more!

**Comment by Cheloggs** [comment]
> 
> 
> Thanks for reporting @Cheloggs! It's been a challenge to capture all the different characters in headings. I'm releasing 0.1.5 which should now grab + and ' and hopefully more!

Thank you for this ready update! I have to report back that 0.1.5 has fixed the `+` character but not the `'` character on my side.

**Comment by shabegom** [comment]
Hm, It is working with straight quotes ('). Are you perhaps using a curly quote? Or is that not a quote character?

**Comment by shabegom** [comment]
the next release will handle curly quotes as well as straight. Thanks!

**Comment by shabegom** [comment]
Totally rewrote how headings are handled. Should support any character you throw at it!
