### ISSUE TITLE
Table is not displayed

### ISSUE THREAD

**Issue by pickleton89** [shabegom/obsidian-reference-count#41]
Hello, Thanks for developing this plugin. I have it installed, but when I click on the count button it opens a view, under the block, that looks like the backlink panel and not formatted table. Originally saw in minimal theme, but still there in other themes so that seems to not be the issue. I don't mind the view, it is actually nice in that I have sorting and other options, but thought I might let you know. Thanks again.

Jeff

**Comment by shabegom** [comment]
Hey Jeff there is a setting to change between the table view and the fancier version
