### ISSUE TITLE
Heading reference won't count non alphabet character headings

### ISSUE THREAD

**Issue by yo-goto** [shabegom/obsidian-reference-count#43]
Hi, thank you for developing a nice plugin.

I tried heading reference feature, but this plugin doesn't seem to support non English language characters like Japanese, Russian, Chinese.
Please support other language characters.

![image](https://user-images.githubusercontent.com/50942816/133885666-3f9cf4bb-9a11-43f3-9a1a-995994df2a5d.png)

Thanks.

**Comment by shabegom** [comment]
0.3.0 should now support non-english characters!!
