### ISSUE TITLE
Add original header "source" in the Search Result Component Counter box, just like how block refs show the source

### ISSUE THREAD

**Issue by GitMurf** [shabegom/obsidian-reference-count#48]
For header references I would like to see the original header in the Search Result Component Counter box just like how block refs show the source. Right now the source Header is not shown in the counter results search component.

**Comment by shabegom** [comment]
Done in 0.3.0!

**Comment by GitMurf** [comment]
Never responded here to say thank you and I love you @shabegom 😘
