### ISSUE TITLE
Counter buttons don't show in 0.13.7?

### ISSUE THREAD

**Issue by DutchPete** [shabegom/obsidian-reference-count#51]
Am I right to say they do not show in the latest Insider version 0.13.7?

**Comment by shabegom** [comment]
If you mean in Live Preview mode then they don't show up there and won't until the obsidian API is updated.

If you mean in Preview mode then they should be showing up.

**Comment by DutchPete** [comment]
Yes, I meant LP. Will that come some time in the future?

**Comment by shabegom** [comment]
As I said, it isn't possible right now and won't be possible unless the obsidian API is updated to support insertion of elements in live preview. As soon as it does, I'll try to support live preview.
