### ISSUE TITLE
Reference counter isn't appearing when block is a bulleted list

### ISSUE THREAD

**Issue by jenningsb2** [shabegom/obsidian-reference-count#55]
Video of issue: https://cln.sh/HK7Ne3

The reference counter works great on a normal block/heading, but when a block in a list item, it doesn't appear.

**Comment by chenlijun99** [comment]
I also met this issue.

**Comment by nicolasmarc1** [comment]
ooh i understand now why it wasn't always working (header worked but not the rest), i have the same issue

**Comment by shabegom** [comment]
Fixed in 0.4.0 release.

**Comment by chuhenry** [comment]
Hello,

This issue appears in v.0.4.3 (using Obsidian v.0.13.28). See below pictures

## Without bulleted list
<img width="912" alt="CleanShot 2022-03-04 at 16 29 25@2x" src="https://user-images.githubusercontent.com/95008347/156727474-0e252aca-b5f6-49ae-bb3e-d6cfe5afd2be.png">

## With bulleted list
<img width="916" alt="CleanShot 2022-03-04 at 16 30 02@2x" src="https://user-images.githubusercontent.com/95008347/156727539-f0d50527-6888-498f-ae3e-b23e607d2871.png">
